# Generated by Django 6.0.4 on 2026-05-05 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='county',
            new_name='country',
        ),
    ]
